/dev/block/bootdevice/by-name/system    /               ext4    ro,barrier=1                              wait,slotselect,first_stage_mount
/dev/block/bootdevice/by-name/vendor    /vendor         ext4    ro,barrier=1                              wait,slotselect,first_stage_mount
/dev/block/bootdevice/by-name/userdata  /data           ext4    noatime,nosuid,nodev,barrier=1,noauto_da_alloc    wait,check,formattable
/dev/block/bootdevice/by-name/misc      /misc           emmc    defaults                                  defaults
