/dev/block/bootdevice/by-name/system    /system     ext4    ro,barrier=1,discard                             wait,slotselect
/dev/block/bootdevice/by-name/vendor    /vendor     ext4    ro,barrier=1,discard                             wait,slotselect
/dev/block/bootdevice/by-name/userdata  /data       ext4    noatime,nosuid,nodev,barrier=1,noauto_da_alloc,discard wait,check,forceencrypt=footer
/dev/block/bootdevice/by-name/misc      /misc       emmc    defaults                                         defaults
/dev/block/bootdevice/by-name/boot      /boot       emmc    defaults                                         defaults
/dev/block/bootdevice/by-name/persist   /persist    ext4    noatime,nosuid,nodev,barrier=1                   defaults
